#!/usr/bin/env ruby

require('yaml')

require_relative('lib/asdf')
require_relative('lib/brew')
require_relative('lib/config')
require_relative('lib/macos')
require_relative('lib/oh_my_zsh')
require_relative('lib/rvm')
require_relative('lib/string')
require_relative('lib/symbolic_links')

puts "\n« Setting macOS Defaults »".bold.blue
macos_config = Config.load('macos')
macos = MacOS.new(macos_config, verbose: true)
macos.defaults!

puts "\n« Installing oh-my-zsh »".bold.blue
omz = OhMyZSH.new(verbose: true)
omz.install!

puts "\n« Creating symbolic links »".bold.blue
symlinks_config = Config.load('symlinks')
links = SymbolicLinks.new(symlinks_config, force: true, verbose: true)
links.create!

puts "\n« Installing homebrew »".bold.blue
homebrew_config = Config.load('homebrew')
brew = Brew.new(homebrew_config, force: true, verbose: true)
brew.install!

puts "\n« Tapping homebrew casks »".bold.blue
brew.tap_casks!

puts "\n« Installing apps via homebrew »".bold.blue
brew.update!
brew.install_apps!

puts "\n« Cleaning up after homebrew »".bold.blue
brew.cleanup!

puts "\n« Installing App Store applications »".bold.blue
macos.install_apps!

puts "\n« Installing asdf plugins »".bold.blue
asdf_config = Config.load('asdf')
asdf = ASDF.new(asdf_config, verbose: true)
asdf.plugins!

puts "\n« Installing rvm »".bold.blue
rvm = RVM.new(verbose: true)
rvm.install!
